config/routes.rb
Rails.application.routes.draw do
  resources :bibliotecas
  resources :livros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biblioteca.rb
class Biblioteca < ApplicationRecord
end

app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to :biblioteca
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bibliotecas_controller.rb
class BibliotecasController < ApplicationController
  before_action :set_biblioteca, only: [:show, :edit, :update, :destroy]

  # GET /bibliotecas
  # GET /bibliotecas.json
  def index
    @bibliotecas = Biblioteca.all
  end

  # GET /bibliotecas/1
  # GET /bibliotecas/1.json
  def show
  end

  # GET /bibliotecas/new
  def new
    @biblioteca = Biblioteca.new
  end

  # GET /bibliotecas/1/edit
  def edit
  end

  # POST /bibliotecas
  # POST /bibliotecas.json
  def create
    @biblioteca = Biblioteca.new(biblioteca_params)

    respond_to do |format|
      if @biblioteca.save
        format.html { redirect_to @biblioteca, notice: 'Biblioteca was successfully created.' }
        format.json { render :show, status: :created, location: @biblioteca }
      else
        format.html { render :new }
        format.json { render json: @biblioteca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bibliotecas/1
  # PATCH/PUT /bibliotecas/1.json
  def update
    respond_to do |format|
      if @biblioteca.update(biblioteca_params)
        format.html { redirect_to @biblioteca, notice: 'Biblioteca was successfully updated.' }
        format.json { render :show, status: :ok, location: @biblioteca }
      else
        format.html { render :edit }
        format.json { render json: @biblioteca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bibliotecas/1
  # DELETE /bibliotecas/1.json
  def destroy
    @biblioteca.destroy
    respond_to do |format|
      format.html { redirect_to bibliotecas_url, notice: 'Biblioteca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biblioteca
      @biblioteca = Biblioteca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biblioteca_params
      params.require(:biblioteca).permit(:nome, :endereco)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:nome, :numero_identificacao, :quantidade, :biblioteca_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bibliotecas_helper.rb
module BibliotecasHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/bibliotecas/_form.html.erb
<%= form_with(model: biblioteca, local: true) do |form| %>
  <% if biblioteca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(biblioteca.errors.count, "error") %> prohibited this biblioteca from being saved:</h2>

      <ul>
      <% biblioteca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bibliotecas/edit.html.erb
<h1>Editing Biblioteca</h1>

<%= render 'form', biblioteca: @biblioteca %>

<%= link_to 'Show', @biblioteca %> |
<%= link_to 'Back', bibliotecas_path %>

app/views/bibliotecas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bibliotecas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bibliotecas.each do |biblioteca| %>
      <tr>
        <td><%= biblioteca.nome %></td>
        <td><%= biblioteca.endereco %></td>
        <td><%= link_to 'Show', biblioteca %></td>
        <td><%= link_to 'Edit', edit_biblioteca_path(biblioteca) %></td>
        <td><%= link_to 'Destroy', biblioteca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biblioteca', new_biblioteca_path %>

app/views/bibliotecas/new.html.erb
<h1>New Biblioteca</h1>

<%= render 'form', biblioteca: @biblioteca %>

<%= link_to 'Back', bibliotecas_path %>

app/views/bibliotecas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @biblioteca.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @biblioteca.endereco %>
</p>

<%= link_to 'Edit', edit_biblioteca_path(@biblioteca) %> |
<%= link_to 'Back', bibliotecas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatalogoBiblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro, local: true) do |form| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :biblioteca %>
    <%= collection_select(:livro, :biblioteca_id, Biblioteca.all, :id, :nome) %>
  </div>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :numero_identificacao %>
    <%= form.number_field :numero_identificacao %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Livros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Número identificação</th>
      <th>Quantidade</th>
      <th>Biblioteca</th>
      <th>Endereço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.nome %></td>
        <td><%= livro.numero_identificacao %></td>
        <td><%= livro.quantidade %></td>
        <td><%= livro.biblioteca.nome %></td>
        <td><%= livro.biblioteca.endereco %></td>
        <td><%= link_to 'Show', livro %></td>
        <td><%= link_to 'Edit', edit_livro_path(livro) %></td>
        <td><%= link_to 'Destroy', livro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Livro', new_livro_path %>

app/views/livros/new.html.erb
<h1>New Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Back', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @livro.nome %>
</p>

<p>
  <strong>Numero identificacao:</strong>
  <%= @livro.numero_identificacao %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @livro.quantidade %>
</p>

<%= link_to 'Edit', edit_livro_path(@livro) %> |
<%= link_to 'Back', livros_path %>